version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-08T15-41-24Z
    command: server /data --console-address ':9001'
    networks:
      - traefik_public
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: ${PASSWORD_32}
      MINIO_BROWSER_REDIRECT_URL: https://miniofrontapp.${DOMAIN}
      MINIO_SERVER_URL: https://miniobackapp.${DOMAIN}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
      labels:
        # Activar traefik
        - traefik.enable=true

        # 🟢 Interfaz Web (console)
        - traefik.http.routers.minio_console.rule=Host(`miniofrontapp.${DOMAIN}`)
        - traefik.http.routers.minio_console.entrypoints=websecure
        - traefik.http.routers.minio_console.tls.certresolver=le
        - traefik.http.routers.minio_console.service=minio_console_svc
        - traefik.http.services.minio_console_svc.loadbalancer.server.port=9001

        # 🟣 API S3
        - traefik.http.routers.minio_s3.rule=Host(`miniobackapp.${DOMAIN}`)
        - traefik.http.routers.minio_s3.entrypoints=websecure
        - traefik.http.routers.minio_s3.tls.certresolver=le
        - traefik.http.routers.minio_s3.service=minio_s3_svc
        - traefik.http.services.minio_s3_svc.loadbalancer.server.port=9000

  minio-init:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - traefik_public
    entrypoint: >
      /bin/sh -c "
      echo '⏳ Esperando MinIO tras Traefik...' && sleep 45 &&
      mc alias set --insecure myminio https://miniobackapp.${DOMAIN} root ${PASSWORD_32} &&
      mc admin config reset myminio identity_openid || true &&
      mc admin service restart myminio || true
      "
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none
      placement:
        constraints:
          - node.role == manager

volumes:
  minio_data:
    external: true

networks:
  traefik_public:
    external: true
