version: '3.8'
services:
  rabbit_mq:
    image: rabbitmq:3.13.7-management
    command: rabbitmq-server
    hostname: rabbit_mq
    networks: [traefik_public]
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${PASSWORD_32}
      RABBITMQ_DEFAULT_VHOST: default
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: ${PASSWORD_32}
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      labels:
        - traefik.enable=true
        - traefik.http.routers.rabbit_mq.rule=Host(`rabbitmqapp.${DOMAIN}`)
        - traefik.http.routers.rabbit_mq.entrypoints=websecure
        - traefik.http.routers.rabbit_mq.tls.certresolver=le
        - traefik.http.services.rabbit_mq.loadbalancer.server.port=15672

volumes:
  rabbitmq_data: { external: true }
networks:
  traefik_public: { external: true }
