version: '3.8'
services:
  redis:
    image: redis:latest
    command: [ "redis-server", "--appendonly", "yes", "--port", "6379" ]
    networks: [general_network]
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      resources:
        limits:
          cpus: '1'
          memory: 1024M

volumes:
  redis_data: { external: true }
networks:
  general_network: { external: true }
